spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
  datasource:
    hikari:
      connection-timeout: '20000'
      idle-timeout: '300000'
      maximum-pool-size: '12'
      max-lifetime: '1200000'
      minimum-idle: '5'
    password: YaE8ba6NMdDyzo5eIrjZ
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://investment.cuqvd0pfludh.ap-south-1.rds.amazonaws.com:3306/kite?verifyServerCertificate=false&autoReconnect=true&useSSL=true
    continue-on-error: 'false'
  batch:
    initialize-schema: never
hibernate:
  allow_update_outside_transaction: 'true'
  dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST,PUT,DELETE,PATCH
    jmx:
      exposure:
        include: health,info
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
server:
  servlet:
    context-path: /users
  port: 8080
